
development:
  adapter: postgresql
  encoding: unicode
  database: epr_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: epr_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: epr_production
  username: postgres
  password: red
  pool: 5

